apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-first-kafka-cluster
  namespace: kafka-sample1
spec:
  kafka:
    version: 3.5.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      log.message.format.version: "3.5"
    storage:
      type: ephemeral # Use ephemeral for a simple, non-persistent test. For production, use 'persistent-claim'.
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
