apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: ingress-sample3
  annotations:
    # Add this line to specify the Ingress class
    kubernetes.io/ingress.class: "nginx"
    # The existing last-applied-configuration annotation can be ignored
spec:
  rules:
    - host: myapp1.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /whoami
            pathType: Prefix
            backend:
              service:
                name: whoami-service
                port:
                  number: 80
